apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          env:
            - name: DB_HOST
              value: {{ .Values.dbHost }}
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.appName }}
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.appName }}
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: ENV_NAME
              value: {{ .Release.Namespace }}
          ports:
            - containerPort: {{ .Values.appPort }}
          resources:
            requests:
              cpu: {{ .Values.cpuRequest }}
              memory: {{ .Values.memoryRequest }}
            limits:
              cpu: {{ .Values.cpuLimit }}
              memory: {{ .Values.memoryLimit }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.appPort }}
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.appPort }}
            initialDelaySeconds: 10
            periodSeconds: 10