appName: nano-app

domain: nano.local

appPort: 5000

# HPA
minReplicas: 2
maxReplicas: 10
cpuTarget: 50

# Postgres
dbHost: postgres
dbName: nanostack
dbUser: nanouser

# Image
image:
  repository: nano-stack-app

# Deployment Resources
cpuRequest: 10m
memoryRequest: 25Mi
cpuLimit: 20m
memoryLimit: 50Mi

# Postgres Resources
PGcpuRequest: 50m
PGmemoryRequest: 100Mi
PGcpuLimit: 100m
PGmemoryLimit: 200Mi

pvcName: postgres-pvc